<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>PUBG-AutoMapper</AssemblyName>
    <RootNamespace>PubgAutoMapper</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Include="tools\adb\**\*" CopyToOutputDirectory="PreserveNewest" Condition="Exists('tools\adb')" />
  </ItemGroup>
</Project>
